package MapeoClases;
// Generated 22 abr 2024 16:57:39 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.registry.StandardServiceRegistry;

/**
 * Fabricantes generated by hbm2java
 */
public class Fabricantes implements java.io.Serializable {

	private String codFab;
	private String nombre;
	private String pais;
	private Set programases = new HashSet(0);

	public Fabricantes() {
	}

	public Fabricantes(String codFab) {
		this.codFab = codFab;
	}

	public Fabricantes(String codFab, String nombre, String pais, Set programases) {
		this.codFab = codFab;
		this.nombre = nombre;
		this.pais = pais;
		this.programases = programases;
	}

	public String getCodFab() {
		return this.codFab;
	}

	public void setCodFab(String codFab) {
		this.codFab = codFab;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set getProgramases() {
		return this.programases;
	}

	public void setProgramases(Set programases) {
		this.programases = programases;
	}
	
	/*
	 * Pregunta dos en el main 
	 */
	
	
	
//	public static void main(String[] args) {
//        
//        SessionFactory sesion = HibernateUtil.getSessionFactory();
//        Session session = sesion.openSession();
//        Transaction transaction = session.beginTransaction();
//
//        try {
//        	
//        	Scanner sc = new Scanner(System.in);
//        	System.out.println("Ingrese el código del fabricante:");
//            String codFab = sc.nextLine();
//            System.out.println("Ingrese el nombre del fabricante:");
//            String nombre = sc.nextLine();
//            System.out.println("Ingrese el país del fabricante:");
//            String pais = sc.nextLine();
//           
//            Fabricantes fabricante = new Fabricantes();
//            fabricante.setCodFab(codFab); 
//            fabricante.setNombre(nombre);
//            fabricante.setPais(pais);
//
//            session.save(fabricante);
//
//            transaction.commit();
//            System.out.println("Fabricante insertado correctamente.");
//            
//        } catch (HibernateException e) {
//            if (transaction != null) {
//                transaction.rollback();
//            }
//            e.printStackTrace();
//        } finally {
//            
//            if (session != null) {
//                session.close();
//            }
//            if (sesion != null) {
//            	sesion.close();
//            }
//            
//        }
//    }

}
